# Generated by Django 6.0.3 on 2026-04-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audituser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='firm',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='firm/logo/'),
        ),
        migrations.AddField(
            model_name='firm',
            name='registration_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
