# Generated by Django 6.0.3 on 2026-04-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_audituser_avatar_firm_logo_firm_registration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audituser',
            name='role',
            field=models.CharField(choices=[('partner', 'Partner'), ('manager', 'Manager'), ('senior', 'Senior Auditor'), ('staff', 'Staff Auditor'), ('it_auditor', 'IT Auditor'), ('qc', 'Quality Control Reviewer'), ('trainee', 'Trainee / Intern')], default='staff', max_length=20),
        ),
    ]
