# Generated by Django 6.0.3 on 2026-04-01 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('internal_control', 'Internal Control Deficiency'), ('financial_reporting', 'Financial Reporting'), ('compliance', 'Compliance Issue'), ('fraud_risk', 'Fraud Risk'), ('it_control', 'IT Control Weakness'), ('operational', 'Operational Issue'), ('other', 'Other')], default='other', max_length=30)),
                ('risk_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('overdue', 'Overdue')], default='open', max_length=20)),
                ('criteria', models.TextField(help_text='What should be happening — the standard or requirement')),
                ('condition', models.TextField(help_text='What is actually happening — the problem observed')),
                ('cause', models.TextField(blank=True, help_text='Why is this happening')),
                ('effect', models.TextField(blank=True, help_text='What is the impact or risk of this issue')),
                ('recommendation', models.TextField(blank=True, help_text='What the client should do to fix this')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings_assigned', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='engagements.engagement')),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagementResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('partial', 'Partially Accepted')], default='accepted', max_length=20)),
                ('response_text', models.TextField(help_text="The client's written response to this finding")),
                ('action_plan', models.TextField(blank=True, help_text='What the client will do to fix this and by when')),
                ('responded_by', models.CharField(blank=True, help_text='Name and title of the person responding on behalf of the client', max_length=255)),
                ('response_date', models.DateField(auto_now_add=True)),
                ('finding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='management_response', to='findings.finding')),
            ],
        ),
    ]
