# Generated by Django 6.0.3 on 2026-04-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('finding_response', 'Client responded to finding'), ('finding_overdue', 'Finding is overdue'), ('workpaper_review', 'Workpaper needs review'), ('finding_resolved', 'Finding resolved'), ('client_pending_approval', 'New client pending approval')], max_length=30),
        ),
    ]
