# Generated by Django 6.0.3 on 2026-04-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
