# Generated by Django 6.0.3 on 2026-04-01 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('audit_type', models.CharField(choices=[('external', 'External Audit'), ('internal', 'Internal Audit'), ('tax', 'Tax Audit'), ('compliance', 'Compliance Audit'), ('special', 'Special Purpose Audit')], default='external', max_length=20)),
                ('financial_year', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('fieldwork', 'Fieldwork'), ('reporting', 'Reporting'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('materiality', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='clients.auditclient')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements_created', to=settings.AUTH_USER_MODEL)),
                ('lead_auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Lead Auditor'), ('senior', 'Senior Auditor'), ('staff', 'Staff Auditor'), ('reviewer', 'Reviewer')], default='staff', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagements.engagement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('engagement', 'user')},
            },
        ),
        migrations.AddField(
            model_name='engagement',
            name='team_members',
            field=models.ManyToManyField(related_name='engagements', through='engagements.EngagementMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
