# Generated by Django 6.0.3 on 2026-04-01 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('section', models.CharField(choices=[('planning', 'Planning'), ('controls', 'Internal Controls'), ('substantive', 'Substantive Procedures'), ('completion', 'Completion'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('reviewed', 'Reviewed'), ('signed_off', 'Signed Off')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('prepared_date', models.DateField(auto_now_add=True)),
                ('reviewed_date', models.DateField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workpapers', to='engagements.engagement')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workpapers_prepared', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workpapers_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='WorkpaperFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='workpapers/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workpapers.workpaper')),
            ],
        ),
    ]
