# Generated by Django 6.0.3 on 2026-04-02 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialityCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(choices=[('revenue', 'Total Revenue'), ('total_assets', 'Total Assets'), ('gross_profit', 'Gross Profit'), ('net_profit', 'Net Profit Before Tax'), ('equity', 'Total Equity'), ('expenditure', 'Total Expenditure')], default='revenue', max_length=20)),
                ('basis_amount', models.DecimalField(decimal_places=2, help_text='The actual financial figure used as basis (UGX)', max_digits=20)),
                ('materiality_percentage', models.DecimalField(decimal_places=2, help_text='Percentage applied to the basis e.g. 5 for 5%', max_digits=5)),
                ('overall_materiality', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20)),
                ('performance_pct', models.DecimalField(decimal_places=2, default=75, help_text='Performance materiality as % of overall e.g. 75', max_digits=5)),
                ('performance_materiality', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20)),
                ('trivial_pct', models.DecimalField(decimal_places=2, default=5, help_text='Clearly trivial as % of overall e.g. 5', max_digits=5)),
                ('trivial_threshold', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20)),
                ('justification', models.TextField(blank=True, help_text='Explain why this basis and percentage were chosen')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiality_approved', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materiality_calc', to='engagements.engagement')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiality_calcs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatioAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('profitability', 'Profitability Ratios'), ('liquidity', 'Liquidity Ratios'), ('efficiency', 'Efficiency Ratios'), ('leverage', 'Leverage / Gearing Ratios'), ('revenue', 'Revenue Analysis'), ('expense', 'Expense Analysis'), ('other', 'Other')], default='other', max_length=20)),
                ('current_year_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('prior_year_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('unit', models.CharField(blank=True, default='%', max_length=20)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True)),
                ('variance_pct', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('explanation', models.TextField(blank=True, help_text='Explain the reason for the movement between years')),
                ('requires_followup', models.BooleanField(default=False, help_text='Flag if this movement is unusual and needs further audit work')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratio_analyses', to='engagements.engagement')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratio_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'ratio_name'],
            },
        ),
    ]
