# Generated by Django 6.0.3 on 2026-04-02 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_risk', models.CharField(choices=[('high', 'High — Extensive audit procedures required'), ('moderate', 'Moderate — Standard audit procedures with selected extensions'), ('low', 'Low — Reduced audit procedures acceptable')], default='moderate', max_length=10)),
                ('overall_materiality', models.DecimalField(blank=True, decimal_places=2, help_text='Overall materiality threshold (UGX)', max_digits=15, null=True)),
                ('performance_materiality', models.DecimalField(blank=True, decimal_places=2, help_text='Performance materiality (usually 75% of overall)', max_digits=15, null=True)),
                ('materiality_basis', models.CharField(blank=True, help_text='e.g. 5% of total revenue, 1% of total assets', max_length=255)),
                ('audit_approach', models.TextField(blank=True, help_text='Overall audit approach and strategy')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_matrices_approved', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_matrix', to='engagements.engagement')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_matrices_prepared', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('revenue', 'Revenue & Receivables'), ('cash', 'Cash & Bank'), ('inventory', 'Inventory & Stock'), ('payroll', 'Payroll & Staff Costs'), ('fixed_assets', 'Fixed Assets'), ('payables', 'Payables & Liabilities'), ('tax', 'Tax & Statutory Compliance'), ('it_controls', 'IT General Controls'), ('financial_close', 'Financial Close & Reporting'), ('other', 'Other')], default='other', max_length=30)),
                ('custom_area_name', models.CharField(blank=True, help_text='Only fill this if area is Other', max_length=100)),
                ('inherent_risk', models.IntegerField(default=0, help_text='0-100. How naturally risky is this area before controls?')),
                ('control_risk', models.IntegerField(default=0, help_text='0-100. How effective are the controls? Higher = weaker controls')),
                ('detection_risk', models.IntegerField(default=0, help_text='0-100. Risk that audit procedures miss a material error')),
                ('overall_risk', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', editable=False, max_length=10)),
                ('key_risks', models.TextField(blank=True, help_text='Describe the specific risks identified in this area')),
                ('audit_response', models.TextField(blank=True, help_text='What audit procedures will address these risks?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_areas', to='engagements.engagement')),
            ],
            options={
                'ordering': ['area'],
                'unique_together': {('engagement', 'area')},
            },
        ),
    ]
